### ISSUE TITLE
Fail to execute UmlsEntityLinker function

### ISSUE THREAD

**Issue by AnnaChu1995** [allenai/scispacy#227]
raise JSONDecodeError("Expecting value", s, err.value) from None
JSONDecodeError: Expecting value
 
Environment: Win10, Spyder

How can I solve this problems?

**Comment by DeNeutoy** [comment]
Please re-open with a full stack trace so we can actually help.

**Comment by AnnaChu1995** [comment]
OK! The following is the error message.

from scispacy.umls_linking import UmlsEntityLinker
linker = UmlsEntityLinker(resolve_abbreviations=True)

Traceback (most recent call last):

  File "<ipython-input-11-fd432066334b>", line 1, in <module>
    linker = UmlsEntityLinker(resolve_abbreviations=True)

  File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\site-packages\scispacy\umls_linking.py", line 68, in __init__
    self.candidate_generator = candidate_generator or CandidateGenerator()

  File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\site-packages\scispacy\candidate_generation.py", line 129, in __init__
    self.umls = umls or UmlsKnowledgeBase()

  File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\site-packages\scispacy\umls_utils.py", line 47, in __init__
    raw = json.load(open(cached_path(file_path)))

  File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)

  File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)

  File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

**Comment by AnnaChu1995** [comment]
> Please re-open with a full stack trace so we can actually help.

OK! The following is the error message.
from scispacy.umls_linking import UmlsEntityLinker
linker = UmlsEntityLinker(resolve_abbreviations=True)

Traceback (most recent call last):

File "", line 1, in
linker = UmlsEntityLinker(resolve_abbreviations=True)

File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\site-packages\scispacy\umls_linking.py", line 68, in init
self.candidate_generator = candidate_generator or CandidateGenerator()

File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\site-packages\scispacy\candidate_generation.py", line 129, in init
self.umls = umls or UmlsKnowledgeBase()

File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\site-packages\scispacy\umls_utils.py", line 47, in init
raw = json.load(open(cached_path(file_path)))

File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\json_init_.py", line 296, in load
parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)

File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\json_init_.py", line 348, in loads
return _default_decoder.decode(s)

File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())

File "C:\Users\ANNA.CHU\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

**Comment by danielkingai2** [comment]
and what python version are you on?

**Comment by AnnaChu1995** [comment]
> I have a feeling this is related to some combination of Windows and python version...but I'm not sure. I was able to load the entity linker on my windows machine just fine. Are you able to load other json files using `json.load`?

c

**Comment by AnnaChu1995** [comment]
> and what python version are you on?

Python 3.7.4
