### ISSUE TITLE
Support for Python 2.7 ?

### ISSUE THREAD

**Issue by Sachit1137** [allenai/scispacy#258]
I wanted to use scispacy in my project which runs on Python 2. But when I run the command : - 

``` python2.7 -m pip install scispacy ```

I get the following error: - 

```ERROR: Package 'scispacy' requires a different Python: 2.7.17 not in '>=3.6.0'```

Is there a way around this so that I can use scispacy in python 2.7?

**Comment by danielkingai2** [comment]
You can clone the repo, change this line: https://github.com/allenai/scispacy/blob/e9f0daeae9a76c644166f852f1d8a101e77d9593/setup.py#L53
and then install the package yourself (`python setup.py install` or `pip install .`). I can't guarantee that it will work on python2.7, but it might, since spacy works on python2.7.

**Comment by Sachit1137** [comment]
Thanks @danielkingai2 got it working.

**Comment by Sachit1137** [comment]
So, now I am trying to run Scispacy in Jython which supports Python 2.7 but I am getting the following error: - 
Any clue regarding this ?

```
ERROR: Command errored out with exit status 1:
     command: /mnt/d/github/jython/bin/jython -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-K8TU7D/preshed/setup.py'"'"'; __file__='"'"'/tmp/pip-install-K8TU7D/preshed/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-QusvHE
         cwd: /tmp/pip-install-K8TU7D/preshed/
    Complete output (35 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-K8TU7D/preshed/setup.py", line 152, in <module>
        setup_package()
      File "/tmp/pip-install-K8TU7D/preshed/setup.py", line 116, in setup_package
        setup(
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 703, in parse_command_line
        result = _Distribution.parse_command_line(self)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 467, in parse_command_line
        args = self._parse_command_opts(parser, args)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 1018, in _parse_command_opts
        nargs = _Distribution._parse_command_opts(self, parser, args)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 838, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2434, in load
        return self.resolve()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2440, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/mnt/d/github/jython/Lib/site-packages/wheel/bdist_wheel.py", line 24, in <module>
        from .pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag, get_platform
      File "/mnt/d/github/jython/Lib/site-packages/wheel/pep425tags.py", line 10, in <module>
        from .macosx_libfile import extract_macosx_min_system_version
      File "/mnt/d/github/jython/Lib/site-packages/wheel/macosx_libfile.py", line 132, in <module>
        segment_command_fields = [
    AttributeError: 'module' object has no attribute 'c_char'
    ----------------------------------------
    ERROR: Failed building wheel for preshed
    Running setup.py clean for preshed
    Building wheel for murmurhash (setup.py): started
    Building wheel for murmurhash (setup.py): finished with status 'done'
    Created wheel for murmurhash: filename=murmurhash-1.0.2-jy27-none-java11_0_8.whl size=5888 sha256=64f485d45727cee76ee7301c0493cef441063f4d8b954c1e0d7ccc9304ea2485
    Stored in directory: /home/sachit/.cache/pip/wheels/15/e4/bd/9a3e3a5ac7ad943ff27bafc3a105ce572b73acd31019549ec2
    Building wheel for thinc (setup.py): started
    Building wheel for thinc (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /mnt/d/github/jython/bin/jython -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-K8TU7D/thinc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-K8TU7D/thinc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1ofVsa
         cwd: /tmp/pip-install-K8TU7D/thinc/
    Complete output (35 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-K8TU7D/thinc/setup.py", line 264, in <module>
        setup_package()
      File "/tmp/pip-install-K8TU7D/thinc/setup.py", line 201, in setup_package
        setup(
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 703, in parse_command_line
        result = _Distribution.parse_command_line(self)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 467, in parse_command_line
        args = self._parse_command_opts(parser, args)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 1018, in _parse_command_opts
        nargs = _Distribution._parse_command_opts(self, parser, args)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 838, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2434, in load
        return self.resolve()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2440, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/mnt/d/github/jython/Lib/site-packages/wheel/bdist_wheel.py", line 24, in <module>
        from .pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag, get_platform
      File "/mnt/d/github/jython/Lib/site-packages/wheel/pep425tags.py", line 10, in <module>
        from .macosx_libfile import extract_macosx_min_system_version
      File "/mnt/d/github/jython/Lib/site-packages/wheel/macosx_libfile.py", line 132, in <module>
        segment_command_fields = [
    AttributeError: 'module' object has no attribute 'c_char'
    ----------------------------------------
    ERROR: Failed building wheel for thinc
    Running setup.py clean for thinc
    Building wheel for blis (setup.py): started
    Building wheel for blis (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /mnt/d/github/jython/bin/jython -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-K8TU7D/blis/setup.py'"'"'; __file__='"'"'/tmp/pip-install-K8TU7D/blis/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_Nn0OT
         cwd: /tmp/pip-install-K8TU7D/blis/
    Complete output (34 lines):
    ('BLIS_COMPILER?', 'None')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-K8TU7D/blis/setup.py", line 239, in <module>
        setup(
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 703, in parse_command_line
        result = _Distribution.parse_command_line(self)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 467, in parse_command_line
        args = self._parse_command_opts(parser, args)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 1018, in _parse_command_opts
        nargs = _Distribution._parse_command_opts(self, parser, args)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 838, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2434, in load
        return self.resolve()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2440, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/mnt/d/github/jython/Lib/site-packages/wheel/bdist_wheel.py", line 24, in <module>
        from .pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag, get_platform
      File "/mnt/d/github/jython/Lib/site-packages/wheel/pep425tags.py", line 10, in <module>
        from .macosx_libfile import extract_macosx_min_system_version
      File "/mnt/d/github/jython/Lib/site-packages/wheel/macosx_libfile.py", line 132, in <module>
        segment_command_fields = [
    AttributeError: 'module' object has no attribute 'c_char'
    ----------------------------------------
    ERROR: Failed building wheel for blis
    Running setup.py clean for blis
    Building wheel for wasabi (setup.py): started
    Building wheel for wasabi (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /mnt/d/github/jython/bin/jython -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-K8TU7D/wasabi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-K8TU7D/wasabi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6GDqjI
         cwd: /tmp/pip-install-K8TU7D/wasabi/
    Complete output (35 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-K8TU7D/wasabi/setup.py", line 41, in <module>
        setup_package()
      File "/tmp/pip-install-K8TU7D/wasabi/setup.py", line 24, in setup_package
        setup(
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 703, in parse_command_line
        result = _Distribution.parse_command_line(self)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 467, in parse_command_line
        args = self._parse_command_opts(parser, args)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 1018, in _parse_command_opts
        nargs = _Distribution._parse_command_opts(self, parser, args)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 838, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2434, in load
        return self.resolve()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2440, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/mnt/d/github/jython/Lib/site-packages/wheel/bdist_wheel.py", line 24, in <module>
        from .pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag, get_platform
      File "/mnt/d/github/jython/Lib/site-packages/wheel/pep425tags.py", line 10, in <module>
        from .macosx_libfile import extract_macosx_min_system_version
      File "/mnt/d/github/jython/Lib/site-packages/wheel/macosx_libfile.py", line 132, in <module>
        segment_command_fields = [
    AttributeError: 'module' object has no attribute 'c_char'
    ----------------------------------------
    ERROR: Failed building wheel for wasabi
    Running setup.py clean for wasabi
    Building wheel for srsly (setup.py): started
    Building wheel for srsly (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /mnt/d/github/jython/bin/jython -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-K8TU7D/srsly/setup.py'"'"'; __file__='"'"'/tmp/pip-install-K8TU7D/srsly/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-JqCOON
         cwd: /tmp/pip-install-K8TU7D/srsly/
    Complete output (35 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-K8TU7D/srsly/setup.py", line 199, in <module>
        setup_package()
      File "/tmp/pip-install-K8TU7D/srsly/setup.py", line 158, in setup_package
        setup(
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 703, in parse_command_line
        result = _Distribution.parse_command_line(self)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 467, in parse_command_line
        args = self._parse_command_opts(parser, args)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 1018, in _parse_command_opts
        nargs = _Distribution._parse_command_opts(self, parser, args)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 838, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2434, in load
        return self.resolve()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2440, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/mnt/d/github/jython/Lib/site-packages/wheel/bdist_wheel.py", line 24, in <module>
        from .pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag, get_platform
      File "/mnt/d/github/jython/Lib/site-packages/wheel/pep425tags.py", line 10, in <module>
        from .macosx_libfile import extract_macosx_min_system_version
      File "/mnt/d/github/jython/Lib/site-packages/wheel/macosx_libfile.py", line 132, in <module>
        segment_command_fields = [
    AttributeError: 'module' object has no attribute 'c_char'
    ----------------------------------------
    ERROR: Failed building wheel for srsly
    Running setup.py clean for srsly
    Building wheel for numpy (setup.py): started
    Building wheel for numpy (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /mnt/d/github/jython/bin/jython -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-K8TU7D/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-K8TU7D/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hiH_Wq
         cwd: /tmp/pip-install-K8TU7D/numpy/
    Complete output (16 lines):
    Running from numpy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-K8TU7D/numpy/setup.py", line 419, in <module>
        setup_package()
      File "/tmp/pip-install-K8TU7D/numpy/setup.py", line 398, in setup_package
        from numpy.distutils.core import setup
      File "/tmp/pip-install-K8TU7D/numpy/numpy/distutils/__init__.py", line 6, in <module>
        from . import ccompiler
      File "/tmp/pip-install-K8TU7D/numpy/numpy/distutils/ccompiler.py", line 18, in <module>
        from numpy.distutils import log
      File "/tmp/pip-install-K8TU7D/numpy/numpy/distutils/log.py", line 10, in <module>
        from .misc_util import (red_text, default_text, cyan_text, green_text,
      File "/tmp/pip-install-K8TU7D/numpy/numpy/distutils/misc_util.py", line 12, in <module>
        import multiprocessing
    ImportError: No module named multiprocessing
    ----------------------------------------
    ERROR: Failed building wheel for numpy
    Running setup.py clean for numpy
    ERROR: Command errored out with exit status 1:
     command: /mnt/d/github/jython/bin/jython -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-K8TU7D/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-K8TU7D/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
         cwd: /tmp/pip-install-K8TU7D/numpy
    Complete output (10 lines):
    Running from numpy source directory.
  
    `setup.py clean` is not supported, use one of the following instead:
  
      - `git clean -xdf` (cleans all files)
      - `git clean -Xdf` (cleans all versioned files, doesn't touch
                          files that aren't checked into the git repo)
  
    Add `--force` to your command to use it anyway if you must (unsupported).
  
    ----------------------------------------
    ERROR: Failed cleaning build dir for numpy
    Building wheel for pathlib (setup.py): started
    Building wheel for pathlib (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /mnt/d/github/jython/bin/jython -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-K8TU7D/pathlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-K8TU7D/pathlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-L42Bzi
         cwd: /tmp/pip-install-K8TU7D/pathlib/
    Complete output (31 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-K8TU7D/pathlib/setup.py", line 6, in <module>
        setup(
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 703, in parse_command_line
        result = _Distribution.parse_command_line(self)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 467, in parse_command_line
        args = self._parse_command_opts(parser, args)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 1018, in _parse_command_opts
        nargs = _Distribution._parse_command_opts(self, parser, args)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 838, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2434, in load
        return self.resolve()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2440, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/mnt/d/github/jython/Lib/site-packages/wheel/bdist_wheel.py", line 24, in <module>
        from .pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag, get_platform
      File "/mnt/d/github/jython/Lib/site-packages/wheel/pep425tags.py", line 10, in <module>
        from .macosx_libfile import extract_macosx_min_system_version
      File "/mnt/d/github/jython/Lib/site-packages/wheel/macosx_libfile.py", line 132, in <module>
        segment_command_fields = [
    AttributeError: 'module' object has no attribute 'c_char'
    ----------------------------------------
    ERROR: Failed building wheel for pathlib
    Running setup.py clean for pathlib
    Building wheel for scandir (setup.py): started
    Building wheel for scandir (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /mnt/d/github/jython/bin/jython -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-K8TU7D/scandir/setup.py'"'"'; __file__='"'"'/tmp/pip-install-K8TU7D/scandir/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-st4OQK
         cwd: /tmp/pip-install-K8TU7D/scandir/
    Complete output (35 lines):
    /mnt/d/github/jython/Lib/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-K8TU7D/scandir/setup.py", line 51, in <module>
        setup(
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 703, in parse_command_line
        result = _Distribution.parse_command_line(self)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 467, in parse_command_line
        args = self._parse_command_opts(parser, args)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 1018, in _parse_command_opts
        nargs = _Distribution._parse_command_opts(self, parser, args)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/distutils/dist.py", line 523, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/mnt/d/github/jython/Lib/site-packages/setuptools/dist.py", line 838, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2434, in load
        return self.resolve()
      File "/mnt/d/github/jython/Lib/site-packages/pkg_resources/__init__.py", line 2440, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/mnt/d/github/jython/Lib/site-packages/wheel/bdist_wheel.py", line 24, in <module>
        from .pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag, get_platform
      File "/mnt/d/github/jython/Lib/site-packages/wheel/pep425tags.py", line 10, in <module>
        from .macosx_libfile import extract_macosx_min_system_version
      File "/mnt/d/github/jython/Lib/site-packages/wheel/macosx_libfile.py", line 132, in <module>
        segment_command_fields = [
    AttributeError: 'module' object has no attribute 'c_char'
    ----------------------------------------
    ERROR: Failed building wheel for scandir
    Running setup.py clean for scandir
  Successfully built cymem murmurhash
  Failed to build preshed thinc blis wasabi srsly numpy pathlib scandir
  DEPRECATION: Could not build wheels for preshed, thinc, blis, wasabi, srsly, numpy, pathlib, scandir which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
  Installing collected packages: setuptools, wheel, cython, cymem, murmurhash, preshed, numpy, blis, wasabi, pathlib, srsly, configparser, contextlib2, zipp, scandir, six, pathlib2, importlib-metadata, catalogue, plac, tqdm, thinc
  ERROR: Exception:
  Traceback (most recent call last):
    File "/mnt/d/github/jython/Lib/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
      status = self.run(options, args)
    File "/mnt/d/github/jython/Lib/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
      return func(self, options, args)
    File "/mnt/d/github/jython/Lib/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
      return func(self, options, args)
    File "/mnt/d/github/jython/Lib/site-packages/pip/_internal/commands/install.py", line 412, in run
      installed = install_given_reqs(
    File "/mnt/d/github/jython/Lib/site-packages/pip/_internal/commands/install.py", line 412, in run
      installed = install_given_reqs(
    File "/mnt/d/github/jython/Lib/site-packages/pip/_internal/req/__init__.py", line 82, in install_given_reqs
      requirement.install(
    File "/mnt/d/github/jython/Lib/site-packages/pip/_internal/req/req_install.py", line 823, in install
      install_wheel(
    File "/mnt/d/github/jython/Lib/site-packages/pip/_internal/operations/install/wheel.py", line 821, in install_wheel
      _install_wheel(
    File "/mnt/d/github/jython/Lib/site-packages/pip/_internal/operations/install/wheel.py", line 703, in _install_wheel
      assert os.path.exists(pyc_path)
  AssertionError
```

**Comment by DeNeutoy** [comment]
Hi @Sachit1137 - python 2.7 reached it's end of life on Jan 1st, 2020 - scispacy certainly won't work with it, because it uses features from python 3.6+ (type hints etc). I'd recommend upgrading to python 3.6+.
