### ISSUE TITLE
UmlsEntityLinker issue with proxy?

### ISSUE THREAD

**Issue by starz10de** [allenai/scispacy#357]
I am using this code for UmlsEntityLinker:
```
import scispacy
import spacy
#import displacy
from scispacy.abbreviation import AbbreviationDetector
from scispacy.umls_linking import UmlsEntityLinker
import os
os.environ['http_proxy'] = "http://proxy.xxx:5555" 
os.environ['https_proxy'] = "https://proxy.xxx:5555" 

#
nlp = spacy.load('en_core_sci_sm')
linker = UmlsEntityLinker(resolve_abbreviations=True)

nlp.add_pipe(linker)
```

However, it seems there is an issue with Proxy even though I am using the same Proxy commands for other tasks without any problem:

```
Your CPU supports instructions that this binary was not compiled to use: SSE3 SSE4.1 SSE4.2 AVX AVX2
For maximum performance, you can install NMSLIB from sources
pip install --no-binary :all: nmslib
Traceback (most recent call last):
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/urllib3/connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/urllib3/connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 429, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/xx/anaconda3/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/home/xx/anaconda3/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/home/xx/anaconda3/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /ai2-s2-scispacy/data/linkers/2020-10-09/umls/tfidf_vectors_sparse.npz (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "linker.py", line 12, in <module>
    linker = UmlsEntityLinker(resolve_abbreviations=True)
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/scispacy/linking.py", line 85, in __init__
    name=linker_name
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/scispacy/candidate_generation.py", line 223, in __init__
    linker_paths=linker_paths, ef_search=ef_search
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/scispacy/candidate_generation.py", line 133, in load_approximate_nearest_neighbours_index
    cached_path(linker_paths.tfidf_vectors)
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/scispacy/file_cache.py", line 36, in cached_path
    return get_from_cache(url_or_filename, cache_dir)
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/scispacy/file_cache.py", line 112, in get_from_cache
    response = requests.head(url, allow_redirects=True)
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/requests/api.py", line 104, in head
    return request('head', url, **kwargs)
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/data/home/xx/scispacy/sci-env/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /ai2-s2-scispacy/data/linkers/2020-10-09/umls/tfidf_vectors_sparse.npz (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1045)')))
```

downloading the  "/ai2-s2-scispacy/data/linkers/2020-10-09/umls/tfidf_vectors_sparse.npz" using pip and the defined Proxy is done without any issue.

**Comment by danielkingai2** [comment]
Are you able to run this line `https://github.com/allenai/scispacy/blob/2290a80cfe0948e48d8ecfbd60064019d57a6874/scispacy/file_cache.py#L112` on that file with your proxy?

Maybe this answer works? https://stackoverflow.com/a/60352993/10459457

**Comment by starz10de** [comment]
> Are you able to run this line `https://github.com/allenai/scispacy/blob/2290a80cfe0948e48d8ecfbd60064019d57a6874/scispacy/file_cache.py#L112` on that file with your proxy?
> 
> Maybe this answer works? https://stackoverflow.com/a/60352993/10459457

After using fresh environment, the proxy issue gone. However, now I go this issue:

`Traceback (most recent call last):
  File "linker.py", line 12, in <module>
    linker = UmlsEntityLinker(resolve_abbreviations=True)
  File "/home/xx/anaconda3/lib/python3.7/site-packages/scispacy/umls_linking.py", line 68, in __init__
    self.candidate_generator = candidate_generator or CandidateGenerator()
  File "/home/xx/anaconda3/lib/python3.7/site-packages/scispacy/candidate_generation.py", line 129, in __init__
    self.umls = umls or UmlsKnowledgeBase()
  File "/home/xx/anaconda3/lib/python3.7/site-packages/scispacy/umls_utils.py", line 47, in __init__
    raw = json.load(open(cached_path(file_path)))
  File "/home/xx/anaconda3/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/xx/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/xx/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/xx/anaconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 79986649 (char 79986648)
`

**Comment by danielkingai2** [comment]
Were you able to resolve this? Could you see if you can load the json file just in a ipython notebook or something?

**Comment by starz10de** [comment]
Unfortunately still the same issue. I can load and work with json files.
I want to share my environment: 

Spacy 2.3.5
Scispacy 0.2.4
en_core_sci_sm 0.2.0 also tried 2.5.0 and 0.3.0

**Comment by danielkingai2** [comment]
with scispacy 0.2.4 you should be using the 0.2.3 models. Could you try that? The way to figure this out is to go to the tag for the release you are using and check the links in the readme (https://github.com/allenai/scispacy/tree/release-v0.2.4#available-models)

**Comment by danielkingai2** [comment]
and you probably need spacy 2.2.1 for scispacy 0.2.4 as well

**Comment by danielkingai2** [comment]
(from checking the requirements file on that tag)

**Comment by starz10de** [comment]
Unfortunately still the same issue. I also checked your post in: https://www.kaggle.com/daking/extracting-entities-linked-to-umls-with-scispacy and tried to use packages versions but no success.

Here the full stack with the list of packages/versions I have:


`/data/home/fsa/Prodigy/Linker/linker-env/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.20.3 when using version 0.22.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/data/home/fsa/Prodigy/Linker/linker-env/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 0.20.3 when using version 0.22.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "linker.py", line 12, in <module>
    linker = UmlsEntityLinker(resolve_abbreviations=True)
  File "/data/home/***/Prodigy/Linker/linker-env/lib/python3.7/site-packages/scispacy/umls_linking.py", line 68, in __init__
    self.candidate_generator = candidate_generator or CandidateGenerator()
  File "/data/home/fsa/Prodigy/Linker/linker-env/lib/python3.7/site-packages/scispacy/candidate_generation.py", line 129, in __init__
    self.umls = umls or UmlsKnowledgeBase()
  File "/data/home/***/Prodigy/Linker/linker-env/lib/python3.7/site-packages/scispacy/umls_utils.py", line 47, in __init__
    raw = json.load(open(cached_path(file_path)))
  File "/home/***/anaconda3/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/***/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/***/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/***/anaconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 79986649 (char 79986648)

****

The installed package:

Package            Version
------------------ ---------
awscli             1.20.5
blis               0.4.1
botocore           1.21.5
catalogue          1.0.0
certifi            2021.5.30
charset-normalizer 2.0.3
colorama           0.4.3
conllu             4.4
cymem              2.0.5
docutils           0.15.2
en-core-sci-sm     0.2.4
idna               3.2
importlib-metadata 4.6.1
jmespath           0.10.0
joblib             1.0.1
murmurhash         1.0.5
nmslib             2.1.1
numpy              1.21.1
pip                21.1.3
plac               0.9.6
preshed            3.0.5
psutil             5.8.0
pyasn1             0.4.8
pybind11           2.6.1
pysbd              0.3.4
python-dateutil    2.8.2
PyYAML             5.4.1
requests           2.26.0
rsa                4.7.2
s3transfer         0.5.0
scikit-learn       0.22.2
scipy              1.7.0
scispacy           0.2.4
setuptools         39.0.1
six                1.16.0
spacy              2.2.1
srsly              1.0.5
thinc              7.1.1
threadpoolctl      2.2.0
tqdm               4.61.2
typing-extensions  3.10.0.0
urllib3            1.26.6
wasabi             0.8.2
zipp               3.5.0
`

For the sklearn warning, I installed the version: 

`DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.`
