### ISSUE TITLE
MeshLinker - Offline - Check failed: The number of stored elements doesn't match the number of datapoints

### ISSUE THREAD

**Issue by gusfelhberg** [allenai/scispacy#379]
Hello!

I've been trying to run a simple code using the MeshLinker on a server (Windows 2012, python 3.8.10) with no internet connection. I have downloaded the files below and stored them under /user/.scispacy
```
MeshLinkerPaths = LinkerPaths(
    ann_index="https://ai2-s2-scispacy.s3-us-west-2.amazonaws.com/data/linkers/2020-10-09/mesh/nmslib_index.bin",  # noqa
    tfidf_vectorizer="https://ai2-s2-scispacy.s3-us-west-2.amazonaws.com/data/linkers/2020-10-09/mesh/tfidf_vectorizer.joblib",  # noqa
    tfidf_vectors="https://ai2-s2-scispacy.s3-us-west-2.amazonaws.com/data/linkers/2020-10-09/mesh/tfidf_vectors_sparse.npz",  # noqa
    concept_aliases_list="https://ai2-s2-scispacy.s3-us-west-2.amazonaws.com/data/linkers/2020-10-09/mesh/concept_aliases.json",  # noqa
)
```
I also changed the candidate_generation.py to point directly to the local files. 

The code I'm trying to run is this below. I'm using a fresh new environment too.

```
import en_core_sci_sm
import scispacy
from scispacy.linking import EntityLinker
nlp = en_core_sci_sm.load()
nlp.add_pipe("scispacy_linker", config={"threshold": 0.8, "linker_name": "mesh"})
```

I keep getting the following error:
```
Check failed: totalElementsStored_ == this->data_.size() The number of stored elements 120302 doesn't match the number of data points 5869671! Did you forget to re-load data?
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    nlp.add_pipe("scispacy_linker",config={"threshold":0.8,"linker_name":"mesh"})
  File "F:\Working\PythonEnvironment\venvs\sal_doc\lib\site-packages\spacy\language.py", line 773, in add_pipe
    pipe_component = self.create_pipe(
  File "F:\Working\PythonEnvironment\venvs\sal_doc\lib\site-packages\spacy\language.py", line 659, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
  File "F:\Working\PythonEnvironment\venvs\sal_doc\lib\site-packages\thinc\config.py", line 727, in resolve
    resolved, _ = cls._make(
  File "F:\Working\PythonEnvironment\venvs\sal_doc\lib\site-packages\thinc\config.py", line 776, in _make
    filled, _, resolved = cls._fill(
  File "F:\Working\PythonEnvironment\venvs\sal_doc\lib\site-packages\thinc\config.py", line 848, in _fill
    getter_result = getter(*args, **kwargs)
  File "F:\Working\PythonEnvironment\venvs\sal_doc\lib\site-packages\scispacy\linking.py", line 84, in __init__
    self.candidate_generator = candidate_generator or CandidateGenerator(
  File "F:\Working\PythonEnvironment\venvs\sal_doc\lib\site-packages\scispacy\candidate_generation.py", line 241, in __init__
    self.ann_index = ann_index or load_approximate_nearest_neighbours_index(
  File "F:\Working\PythonEnvironment\venvs\sal_doc\lib\site-packages\scispacy\candidate_generation.py", line 160, in load_approximate_nearest_neighbours_index
    ann_index.loadIndex(cached_path(linker_paths.ann_index))
RuntimeError: Check failed: The number of stored elements 120302 doesn't match the number of data points 5869671! Did you forget to re-load data?
```

I have it running with no problem in a different environment with internet connection. So I also have tried copying the files downloaded by the script instead of those I downloaded using the browser. The difference is that the file names contains a hash (?), like this:

```
1a5445257d097c1d2a9eba040029329993377ebc82785ee9ad18ed2b86f7fc7d.bc94249222c42b975a55db3a2b6f7badffe87b809e02f16907fca650f787f2f3.concept_aliases.json
...
```

After copying those files to the environment with no internet access, repointing them in candidate_generator,py, the error continues.

If I try to run the same code, but using 'umls' instead of 'mesh' (and also downloading the files manually, copying to the server and changing in candidate_generator.py), it works!

Am I missing something?

**Comment by danielkingai2** [comment]
The differential in size mentioned in the error make me think you are somehow loading some resources for mesh and some for umls. Could you just triple check that you have the right paths for mesh, and those are the files actually getting loaded, before we dig deeper?

**Comment by gusfelhberg** [comment]
I think you are correct. I redownloaded all the files, deleted the previous folder and copied again and now it seems to be working. Thanks! I'll close the issue.
