### ISSUE TITLE
About Tanse

### ISSUE THREAD

**Issue by rhyhck** [allenai/scispacy#510]
Hi, When I run the Transe，I meet a problem as follow:

Traceback (most recent call last):
  File "prepro/prepro_pretraining_data.py", line 433, in <module>
    main()
  File "prepro/prepro_pretraining_data.py", line 419, in main
    train_transe()  #使用transe生成实体embedding并保存结果  
  File "/data/renhongyi/ARL/ARL-master/prepro/OpenKE/train_transe.py", line 19, in train_transe
    train_dataloader = TrainDataLoader(
  File "/data/renhongyi/ARL/ARL-master/prepro/OpenKE/openke/data/TrainDataLoader.py", line 42, in __init__
    self.lib = ctypes.cdll.LoadLibrary(base_file)
  File "/data/renhongyi/.conda/envs/ARL/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/data/renhongyi/.conda/envs/ARL/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /data/renhongyi/ARL/ARL-master/prepro/OpenKE/openke/release/Base.so: cannot open shared object file: No such file or directory

Could you tell me how to resolve?

**Comment by dakinggg** [comment]
Wrong repo
