### ISSUE TITLE
GPU Support for scispacy

### ISSUE THREAD

**Issue by articuno12** [allenai/scispacy#81]
Is GPU support available for scispacy?

**Comment by danielkingai2** [comment]
We have been running everything on CPU (and this is very fast because spaCy is very fast). That being said, spaCy does support GPU, and if you install and use spacy based on the instructions here (https://spacy.io/usage/#gpu), spaCy should use GPU, and so scispaCy should use GPU. However, I am not sure what speedup you would expect from using GPU, but I did confirm that there is some gpu utilization if you load a scispacy model like so (after following the instructions to install spacy with gpu)
```
import spacy
spacy.require_gpu()
nlp = spacy.load('en_core_sci_sm')
doc = nlp("Some text")
```

**Comment by articuno12** [comment]
spacy GPU works a lot faster than spacy for multiple queries. 
I tried the above method, but it gives the following error.

> doc.similarity(doc2)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "doc.pyx", line 322, in spacy.tokens.doc.Doc.similarity
>   File "doc.pyx", line 386, in spacy.tokens.doc.Doc.vector_norm.__get__
>   File "doc.pyx", line 361, in spacy.tokens.doc.Doc.vector.__get__
>   File "cupy/core/core.pyx", line 1741, in cupy.core.core.ndarray.__array_ufunc__
>   File "cupy/core/_kernel.pyx", line 787, in cupy.core._kernel.ufunc.__call__
>   File "cupy/core/_kernel.pyx", line 86, in cupy.core._kernel._preprocess_args
> TypeError: Unsupported type <class 'numpy.ndarray'>

**Comment by danielkingai2** [comment]
Try it a new conda environment and first installing spacy with gpu with `pip install -U spacy[cuda92]` or with whatever version of cuda you have. and then installing `pip install scispacy` and `pip install <scispacy_model_link>`. Those were the steps I followed that worked for me.

**Comment by articuno12** [comment]
Still similarity function not working.

**Comment by danielkingai2** [comment]
hmm, I was actually able to reproduce with the spacy `en_core_web_md` model. It seems that this an issue with spacy, so i've opened an issue on the spacy repo https://github.com/explosion/spaCy/issues/3348

**Comment by danielkingai2** [comment]
PR open to fix this (https://github.com/explosion/spaCy/pull/3362), when spaCy releases 2.1 and we upgrade to that version this issue will be fixed.

**Comment by danielkingai2** [comment]
This should be fixed in version `0.2.0` which is now up. This version of `scispacy` is compatible with version `2.1.3` of `spacy`
