### ISSUE TITLE
Syntax error(python 3.5)

### ISSUE THREAD

**Issue by sub10** [allenai/scispacy#85]
When I am running the example code available in the scispacy site, I am getting this error..
Could you help me solve the problem? 

(env) vk@vk:~$ python test1.py 
Traceback (most recent call last):
  File "test1.py", line 5, in <module>
    nlp = spacy.load("en_core_sci_sm")
  File "/home/vk/env/lib/python3.5/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/home/vk/env/lib/python3.5/site-packages/spacy/util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/vk/env/lib/python3.5/site-packages/spacy/util.py", line 134, in load_model_from_package
    cls = importlib.import_module(name)
  File "/home/vk/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/vk/env/lib/python3.5/site-packages/en_core_sci_sm/__init__.py", line 7, in <module>
    from scispacy.custom_sentence_segmenter import combined_rule_sentence_segmenter
  File "/home/vk/env/lib/python3.5/site-packages/scispacy/custom_sentence_segmenter.py", line 15
    prev_token_1: Token = None
                ^
SyntaxError: invalid syntax

**Comment by danielkingai2** [comment]
Is it possible for you to try with python 3.6?

**Comment by DeNeutoy** [comment]
Hmm I think this is because python 3.5 doesn't support inline type hints. We should update the readme.

**Comment by sub10** [comment]
Thanx.. I have tried it in python 3.6.. Now it is working

**Comment by DeNeutoy** [comment]
Great!
